/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_automatak_dnp3_impl_DNP3ManagerImpl */

#ifndef _Included_com_automatak_dnp3_impl_DNP3ManagerImpl
#define _Included_com_automatak_dnp3_impl_DNP3ManagerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_automatak_dnp3_impl_DNP3ManagerImpl
 * Method:    addTCPClient
 * Signature: (Ljava/lang/String;Lcom/automatak/dnp3/LogLevel;JLjava/lang/String;I)Lcom/automatak/dnp3/Channel;
 */
JNIEXPORT jobject JNICALL Java_com_automatak_dnp3_impl_DNP3ManagerImpl_addTCPClient
  (JNIEnv *, jobject, jstring, jobject, jlong, jstring, jint);

/*
 * Class:     com_automatak_dnp3_impl_DNP3ManagerImpl
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_DNP3ManagerImpl_shutdown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
