/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_automatak_dnp3_impl_DataObserverImpl */

#ifndef _Included_com_automatak_dnp3_impl_DataObserverImpl
#define _Included_com_automatak_dnp3_impl_DataObserverImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_automatak_dnp3_impl_DataObserverImpl
 * Method:    native_start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_DataObserverImpl_native_1start
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_automatak_dnp3_impl_DataObserverImpl
 * Method:    native_update_bi
 * Signature: (JZBJJ)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_DataObserverImpl_native_1update_1bi
  (JNIEnv *, jobject, jlong, jboolean, jbyte, jlong, jlong);

/*
 * Class:     com_automatak_dnp3_impl_DataObserverImpl
 * Method:    native_update_ai
 * Signature: (JDBJJ)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_DataObserverImpl_native_1update_1ai
  (JNIEnv *, jobject, jlong, jdouble, jbyte, jlong, jlong);

/*
 * Class:     com_automatak_dnp3_impl_DataObserverImpl
 * Method:    native_update_c
 * Signature: (JJBJJ)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_DataObserverImpl_native_1update_1c
  (JNIEnv *, jobject, jlong, jlong, jbyte, jlong, jlong);

/*
 * Class:     com_automatak_dnp3_impl_DataObserverImpl
 * Method:    native_update_fc
 * Signature: (JJBJJ)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_DataObserverImpl_native_1update_1fc
  (JNIEnv *, jobject, jlong, jlong, jbyte, jlong, jlong);

/*
 * Class:     com_automatak_dnp3_impl_DataObserverImpl
 * Method:    native_update_bos
 * Signature: (JZBJJ)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_DataObserverImpl_native_1update_1bos
  (JNIEnv *, jobject, jlong, jboolean, jbyte, jlong, jlong);

/*
 * Class:     com_automatak_dnp3_impl_DataObserverImpl
 * Method:    native_update_aos
 * Signature: (JDBJJ)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_DataObserverImpl_native_1update_1aos
  (JNIEnv *, jobject, jlong, jdouble, jbyte, jlong, jlong);

/*
 * Class:     com_automatak_dnp3_impl_DataObserverImpl
 * Method:    native_end
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_DataObserverImpl_native_1end
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
