/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_automatak_dnp3_impl_CommandProcessorImpl */

#ifndef _Included_com_automatak_dnp3_impl_CommandProcessorImpl
#define _Included_com_automatak_dnp3_impl_CommandProcessorImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_automatak_dnp3_impl_CommandProcessorImpl
 * Method:    selectAndOperateCROB
 * Signature: (JISJJIJLcom/automatak/dnp3/impl/CommandResultCallback;)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_CommandProcessorImpl_selectAndOperateCROB
(JNIEnv*, jobject, jlong, jint, jshort, jlong, jlong, jint, jlong, jobject);

/*
 * Class:     com_automatak_dnp3_impl_CommandProcessorImpl
 * Method:    directOperateCROB
 * Signature: (JISJJIJLcom/automatak/dnp3/impl/CommandResultCallback;)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_CommandProcessorImpl_directOperateCROB
(JNIEnv*, jobject, jlong, jint, jshort, jlong, jlong, jint, jlong, jobject);

/*
 * Class:     com_automatak_dnp3_impl_CommandProcessorImpl
 * Method:    selectAndOperateAnalogInt32
 * Signature: (JIIJLcom/automatak/dnp3/impl/CommandResultCallback;)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_CommandProcessorImpl_selectAndOperateAnalogInt32
(JNIEnv*, jobject, jlong, jint, jint, jlong, jobject);

/*
 * Class:     com_automatak_dnp3_impl_CommandProcessorImpl
 * Method:    directOperateAnalogInt32
 * Signature: (JIIJLcom/automatak/dnp3/impl/CommandResultCallback;)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_CommandProcessorImpl_directOperateAnalogInt32
(JNIEnv*, jobject, jlong, jint, jint, jlong, jobject);

/*
 * Class:     com_automatak_dnp3_impl_CommandProcessorImpl
 * Method:    selectAndOperateAnalogInt16
 * Signature: (JSIJLcom/automatak/dnp3/impl/CommandResultCallback;)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_CommandProcessorImpl_selectAndOperateAnalogInt16
(JNIEnv*, jobject, jlong, jshort, jint, jlong, jobject);

/*
 * Class:     com_automatak_dnp3_impl_CommandProcessorImpl
 * Method:    directOperateAnalogInt16
 * Signature: (JSIJLcom/automatak/dnp3/impl/CommandResultCallback;)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_CommandProcessorImpl_directOperateAnalogInt16
(JNIEnv*, jobject, jlong, jshort, jint, jlong, jobject);

/*
 * Class:     com_automatak_dnp3_impl_CommandProcessorImpl
 * Method:    selectAndOperateAnalogFloat32
 * Signature: (JFIJLcom/automatak/dnp3/impl/CommandResultCallback;)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_CommandProcessorImpl_selectAndOperateAnalogFloat32
(JNIEnv*, jobject, jlong, jfloat, jint, jlong, jobject);

/*
 * Class:     com_automatak_dnp3_impl_CommandProcessorImpl
 * Method:    directOperateAnalogFloat32
 * Signature: (JFIJLcom/automatak/dnp3/impl/CommandResultCallback;)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_CommandProcessorImpl_directOperateAnalogFloat32
(JNIEnv*, jobject, jlong, jfloat, jint, jlong, jobject);

/*
 * Class:     com_automatak_dnp3_impl_CommandProcessorImpl
 * Method:    selectAndOperateAnalogDouble64
 * Signature: (JDIJLcom/automatak/dnp3/impl/CommandResultCallback;)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_CommandProcessorImpl_selectAndOperateAnalogDouble64
(JNIEnv*, jobject, jlong, jdouble, jint, jlong, jobject);

/*
 * Class:     com_automatak_dnp3_impl_CommandProcessorImpl
 * Method:    directOperateAnalogDouble64
 * Signature: (JDIJLcom/automatak/dnp3/impl/CommandResultCallback;)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_CommandProcessorImpl_directOperateAnalogDouble64
(JNIEnv*, jobject, jlong, jdouble, jint, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
