/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_automatak_dnp3_impl_DatabaseImpl */

#ifndef _Included_com_automatak_dnp3_impl_DatabaseImpl
#define _Included_com_automatak_dnp3_impl_DatabaseImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_automatak_dnp3_impl_DatabaseImpl
 * Method:    new_update_builder_native
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_automatak_dnp3_impl_DatabaseImpl_new_1update_1builder_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_automatak_dnp3_impl_DatabaseImpl
 * Method:    delete_update_builder_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_DatabaseImpl_delete_1update_1builder_1native
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_automatak_dnp3_impl_DatabaseImpl
 * Method:    update_binary_native
 * Signature: (JZBLcom/automatak/dnp3/DNPTime;II)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_DatabaseImpl_update_1binary_1native
  (JNIEnv *, jobject, jlong, jboolean, jbyte, jobject, jint, jint);

/*
 * Class:     com_automatak_dnp3_impl_DatabaseImpl
 * Method:    update_double_binary_native
 * Signature: (JIBLcom/automatak/dnp3/DNPTime;II)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_DatabaseImpl_update_1double_1binary_1native
  (JNIEnv *, jobject, jlong, jint, jbyte, jobject, jint, jint);

/*
 * Class:     com_automatak_dnp3_impl_DatabaseImpl
 * Method:    update_analog_native
 * Signature: (JDBLcom/automatak/dnp3/DNPTime;II)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_DatabaseImpl_update_1analog_1native
  (JNIEnv *, jobject, jlong, jdouble, jbyte, jobject, jint, jint);

/*
 * Class:     com_automatak_dnp3_impl_DatabaseImpl
 * Method:    update_counter_native
 * Signature: (JJBLcom/automatak/dnp3/DNPTime;II)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_DatabaseImpl_update_1counter_1native
  (JNIEnv *, jobject, jlong, jlong, jbyte, jobject, jint, jint);

/*
 * Class:     com_automatak_dnp3_impl_DatabaseImpl
 * Method:    freeze_counter_native
 * Signature: (JIZI)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_DatabaseImpl_freeze_1counter_1native
  (JNIEnv *, jobject, jlong, jint, jboolean, jint);

/*
 * Class:     com_automatak_dnp3_impl_DatabaseImpl
 * Method:    update_bo_status_native
 * Signature: (JZBLcom/automatak/dnp3/DNPTime;II)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_DatabaseImpl_update_1bo_1status_1native
  (JNIEnv *, jobject, jlong, jboolean, jbyte, jobject, jint, jint);

/*
 * Class:     com_automatak_dnp3_impl_DatabaseImpl
 * Method:    update_ao_status_native
 * Signature: (JDBLcom/automatak/dnp3/DNPTime;II)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_DatabaseImpl_update_1ao_1status_1native
  (JNIEnv *, jobject, jlong, jdouble, jbyte, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
