/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_automatak_dnp3_impl_DNP3ManagerImpl */

#ifndef _Included_com_automatak_dnp3_impl_DNP3ManagerImpl
#define _Included_com_automatak_dnp3_impl_DNP3ManagerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_automatak_dnp3_impl_DNP3ManagerImpl
 * Method:    create_native_manager
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_automatak_dnp3_impl_DNP3ManagerImpl_create_1native_1manager
  (JNIEnv *, jobject);

/*
 * Class:     com_automatak_dnp3_impl_DNP3ManagerImpl
 * Method:    destroy_native_manager
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_DNP3ManagerImpl_destroy_1native_1manager
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
