/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_automatak_dnp3_impl_ManagerImpl */

#ifndef _Included_com_automatak_dnp3_impl_ManagerImpl
#define _Included_com_automatak_dnp3_impl_ManagerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_automatak_dnp3_impl_ManagerImpl
 * Method:    create_native_manager
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_automatak_dnp3_impl_ManagerImpl_create_1native_1manager
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_automatak_dnp3_impl_ManagerImpl
 * Method:    destroy_native_manager
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_ManagerImpl_destroy_1native_1manager
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_automatak_dnp3_impl_ManagerImpl
 * Method:    get_native_channel_tcp_client
 * Signature: (JLjava/lang/String;Lcom/automatak/dnp3/LogLevel;JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_automatak_dnp3_impl_ManagerImpl_get_1native_1channel_1tcp_1client
  (JNIEnv *, jobject, jlong, jstring, jobject, jlong, jstring, jint);

/*
 * Class:     com_automatak_dnp3_impl_ManagerImpl
 * Method:    get_native_channel_tcp_server
 * Signature: (JLjava/lang/String;Lcom/automatak/dnp3/LogLevel;JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_automatak_dnp3_impl_ManagerImpl_get_1native_1channel_1tcp_1server
  (JNIEnv *, jobject, jlong, jstring, jobject, jlong, jstring, jint);

/*
 * Class:     com_automatak_dnp3_impl_ManagerImpl
 * Method:    get_native_channel_serial
 * Signature: (JLjava/lang/String;Lcom/automatak/dnp3/LogLevel;JLjava/lang/String;IIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_automatak_dnp3_impl_ManagerImpl_get_1native_1channel_1serial
  (JNIEnv *, jobject, jlong, jstring, jobject, jlong, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     com_automatak_dnp3_impl_ManagerImpl
 * Method:    native_add_log_subscriber
 * Signature: (JLcom/automatak/dnp3/LogSubscriber;)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_ManagerImpl_native_1add_1log_1subscriber
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
