/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_automatak_dnp3_impl_VTOEndpointImpl */

#ifndef _Included_com_automatak_dnp3_impl_VTOEndpointImpl
#define _Included_com_automatak_dnp3_impl_VTOEndpointImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_automatak_dnp3_impl_VTOEndpointImpl
 * Method:    shutdown_native_endpoint
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_VTOEndpointImpl_shutdown_1native_1endpoint
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
